config/routes.rb
Quiz::Application.routes.draw do

  resources :questions

  resources :levels

  resources :operators
  
  resources :homes

  root to: 'home#index', as: 'home'

end

app/models/home.rb
class Home < ActiveRecord::Base
  attr_accessible :description, :lower_range, :upper_range, :operator
end

app/models/level.rb
class Level < ActiveRecord::Base
  attr_accessible :description, :lower_range, :upper_range
end

app/models/operator.rb
class Operator < ActiveRecord::Base
  attr_accessible :description, :operator
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :answer, :difficulty, :first_num, :question_type, :second_num
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def show
    #stuff here
  end
  
  def create
  end
  
  def do
      if params[:exp] = '1' #remember that params come back as strings
        do_something
      elsif params[:exp] = '2'
        do_something_else
      else
        handle_the_no_default_radio_button_case # if you want one to be checked, supply true as the third parameter
      end

      respond_to do |format|
        format.js {
      render :update do |page|
        page.replace_html or some other reponse
      end
      }
      end
      format.html { redirect_to questions_url }
  end
  
  def index
    @operator = Operator.all
    @level = Level.all

    respond_to do |format|
    format.html # index.html.erb
    format.json { render json: @levels }
    format.json { render json: @operator }
    end
  end
  
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  # GET /levels
  # GET /levels.json
  def index
    @levels = Level.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @levels }
    end
  end

  # GET /levels/1
  # GET /levels/1.json
  def show
    @level = Level.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @level }
    end
  end

  # GET /levels/new
  # GET /levels/new.json
  def new
    @level = Level.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @level }
    end
  end

  # GET /levels/1/edit
  def edit
    @level = Level.find(params[:id])
  end

  # POST /levels
  # POST /levels.json
  def create
    @level = Level.new(params[:level])

    respond_to do |format|
      if @level.save
        format.html { redirect_to @level, notice: 'Level was successfully created.' }
        format.json { render json: @level, status: :created, location: @level }
      else
        format.html { render action: "new" }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /levels/1
  # PUT /levels/1.json
  def update
    @level = Level.find(params[:id])

    respond_to do |format|
      if @level.update_attributes(params[:level])
        format.html { redirect_to @level, notice: 'Level was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1
  # DELETE /levels/1.json
  def destroy
    @level = Level.find(params[:id])
    @level.destroy

    respond_to do |format|
      format.html { redirect_to levels_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/operators_controller.rb
class OperatorsController < ApplicationController
  # GET /operators
  # GET /operators.json
  def index
    @operators = Operator.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @operators }
    end
  end

  # GET /operators/1
  # GET /operators/1.json
  def show
    @operator = Operator.find(params[:id])
    @oper1 = rand(1..6)
    @oper3 = rand(1..6)
    
    if @operator.id = 0
      @ans = @oper1 + @oper3
    end
    
    if @operator.id = 1
      @ans = @oper1 - @oper3
    end
    
    @level = Level.all
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @operator }
    end
  end

  # GET /operators/new
  # GET /operators/new.json
  def new
    @operator = Operator.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @operator }
    end
  end

  # GET /operators/1/edit
  def edit
    @operator = Operator.find(params[:id])
  end

  # POST /operators
  # POST /operators.json
  def create
    @operator = Operator.new(params[:operator])

    respond_to do |format|
      if @operator.save
        format.html { redirect_to @operator, notice: 'Operator was successfully created.' }
        format.json { render json: @operator, status: :created, location: @operator }
      else
        format.html { render action: "new" }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /operators/1
  # PUT /operators/1.json
  def update
    @operator = Operator.find(params[:id])

    respond_to do |format|
      if @operator.update_attributes(params[:operator])
        format.html { redirect_to @operator, notice: 'Operator was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operators/1
  # DELETE /operators/1.json
  def destroy
    @operator = Operator.find(params[:id])
    @operator.destroy

    respond_to do |format|
      format.html { redirect_to operators_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/index.html.erb
<h1>Quiz Home Page</h1>

<p>
<label><%= "Pick a question type" %></label>
<table>
<% @operator.each do |operator| %>
  <tr>
	<td>
		<input type="radio"
		id = <%= operator.description %>
		name = "operatorq"
		value =  <td><%= operator.description %></td>
  </tr>
<% end %>

</table>
</p>

<p>
	<%= "... and pick a difficulty "%>
<table>
<% @level.each do |level| %>
  <tr>
	<td>
		<input type="radio"
		id = <%= level.id %>
		name = @levelq
		value = <td><%= level.description %></td>
  </tr>
<% end %>
</table>
</p>

<%= link_to "Generate a question", new_question_path %>
<%= link_to 'Submit now', :url => {:action=>"do"}, :submit => 'operatorq', :remote => true %>

app/views/home/show.html.erb
<h1>This is the Show Page</h1>

<p>
	You picked a <% operatorq %> question
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/levels/_form.html.erb
<%= form_for(@level) do |f| %>
  <% if @level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@level.errors.count, "error") %> prohibited this level from being saved:</h2>

      <ul>
      <% @level.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :lower_range %><br />
    <%= f.number_field :lower_range %>
  </div>
  <div class="field">
    <%= f.label :upper_range %><br />
    <%= f.number_field :upper_range %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/levels/edit.html.erb
<h1>Editing level</h1>

<%= render 'form' %>

<%= link_to 'Show', @level %> |
<%= link_to 'Back', levels_path %>

app/views/levels/index.html.erb
<h1>Listing levels</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Lower range</th>
    <th>Upper range</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @levels.each do |level| %>
  <tr>
    <td><%= level.description %></td>
    <td><%= level.lower_range %></td>
    <td><%= level.upper_range %></td>
    <td><%= link_to 'Show', level %></td>
    <td><%= link_to 'Edit', edit_level_path(level) %></td>
    <td><%= link_to 'Destroy', level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Level', new_level_path %>

app/views/levels/new.html.erb
<h1>New level</h1>

<%= render 'form' %>

<%= link_to 'Back', levels_path %>

app/views/levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @level.description %>
</p>

<p>
  <b>Lower range:</b>
  <%= @level.lower_range %>
</p>

<p>
  <b>Upper range:</b>
  <%= @level.upper_range %>
</p>


<%= link_to 'Edit', edit_level_path(@level) %> |
<%= link_to 'Back', levels_path %>

app/views/operators/_form.html.erb
<%= form_for(@operator) do |f| %>
  <% if @operator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operator.errors.count, "error") %> prohibited this operator from being saved:</h2>

      <ul>
      <% @operator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :operator %><br />
    <%= f.text_area :operator %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operators/edit.html.erb
<h1>Editing operator</h1>

<%= render 'form' %>

<%= link_to 'Show', @operator %> |
<%= link_to 'Back', operators_path %>

app/views/operators/index.html.erb
<h1>Listing operators</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Operator</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @operators.each do |operator| %>
  <tr>
    <td><%= operator.description %></td>
    <td><%= operator.operator %></td>
    <td><%= link_to 'Show', operator %></td>
    <td><%= link_to 'Edit', edit_operator_path(operator) %></td>
    <td><%= link_to 'Destroy', operator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Operator', new_operator_path %>

app/views/operators/new.html.erb
<h1>New operator</h1>

<%= render 'form' %>

<%= link_to 'Back', operators_path %>

app/views/operators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @operator.description %>
</p>

<p>
  <b>Operator:</b>
  <%= @operator.operator %>
</p>

<p>
	<b>Level:</b>

</p>

<p>
	<b>Edited:</b>
	<li><%= "What is " %> <%= @oper1 %> <%= " " %> <%= @operator.operator %> <%= " " %> <%= @oper3 %> ?</li>
	<li><%= "The answer is " %> <%= @ans %></li>
</p>


<%= link_to 'Edit', edit_operator_path(@operator) %> |
<%= link_to 'Back', operators_path %>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question_type %><br />
    <%= f.text_area :question_type %>
  </div>
  <div class="field">
    <%= f.label :difficulty %><br />
    <%= f.number_field :difficulty %>
  </div>
  <div class="field">
    <%= f.label :first_num %><br />
    <%= f.number_field :first_num %>
  </div>
  <div class="field">
    <%= f.label :second_num %><br />
    <%= f.number_field :second_num %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.number_field :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Here's Your Question</h1>

<table>
  <tr>
    <th>Question type</th>
    <th>Difficulty</th>
    <th>First num</th>
    <th>Second num</th>
    <th>Answer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.question_type %></td>
    <td><%= question.difficulty %></td>
    <td><%= question.first_num %></td>
    <td><%= question.second_num %></td>
    <td><%= question.answer %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<% @operatorq %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question type:</b>
  <%= @question.question_type %>
</p>

<p>
  <b>Difficulty:</b>
  <%= @question.difficulty %>
</p>

<p>
  <b>First num:</b>
  <%= @question.first_num %>
</p>

<p>
  <b>Second num:</b>
  <%= @question.second_num %>
</p>

<p>
  <b>Answer:</b>
  <%= @question.answer %>
</p>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>